[40]: Wait for vault pods to have ip addresses before unsealing them
pyToshka/vault-autounseal pull request #41
Opened 2024-04-26 10:40 UTC by sfc-gh-gmerticariu

If the vault auto-unsealed starts as fast as the vault pods, there is a risk that the vault pod does not yet have an IP address assigned. This changes are adding a wait, in case the IP address is not present in the vault pod.

2024-04-26 12:30 UTC, pyToshka requested changes

2024-04-26 12:30 UTC, pyToshka commented on app.py
> +        print("Pod retrieval max retries cannot be lower than 1: {}", pod_retrieval_max_retries)
please use logger

2024-04-26 12:30 UTC, pyToshka commented on app.py
> +    if len(pod_list.items) == 0:
Local variable 'pod_list' might be referenced before assignment

2024-04-26 12:30 UTC, pyToshka commented on app.py
> +    for _ in range(pod_retrieval_max_retries):
Not clear logic

2024-04-26 12:30 UTC, pyToshka commented on app.py
> +    exit(2)
Are you sure for exit 2? 
in this case, pod will restart

2024-04-26 12:30 UTC, pyToshka commented on app.py
> +          [p.metadata.name for p in pod_list.items if p.status.pod_ip is None])
Maybe no need to use "p" and use something like pod?

2024-04-26 12:57 UTC, sfc-gh-gmerticariu commented on app.py
> +    exit(2)
I was thinking the best here would be to restart pod so it goes into a CrashLoopBackoff, so people check the logs to see what the issue was. How do you handle the cases where there is nothing to unseal or the vault pods are not ready? Do you want to silently fail, or do you agree with my proposal?

2024-04-26 12:58 UTC, sfc-gh-gmerticariu commented on app.py
> +    for _ in range(pod_retrieval_max_retries):
I adapted it to be clearer

2024-04-26 12:59 UTC, sfc-gh-gmerticariu commented on app.py
> +          [p.metadata.name for p in pod_list.items if p.status.pod_ip is None])
I was using "p" here because there is a "pod" declared in the global context, so there might be a linter error with variable shadowing.

2024-04-26 19:34 UTC, pyToshka commented on app.py
> +    exit(2)
I agree, please add logging for exit reason.

2024-04-29 07:58 UTC, sfc-gh-gmerticariu commented on app.py
> +    exit(2)
Is using `logger` enough or do you want me to `print` the message?

2024-04-29 08:32 UTC, pyToshka commented on app.py
> +    exit(2)
Please use logger

2024-04-29 09:09 UTC, sfc-gh-gmerticariu commented on app.py
> +    exit(2)
That's already implemented. Could you please review the code again?

2024-04-30 10:27 UTC, sfc-gh-gmerticariu commented
@pyToshka could you please let me know what the error from SnoarCloud is? Thank you!

2024-05-03 06:13 UTC, pyToshka commented
@sfc-gh-gmerticariu  no worries about Sonar

2024-05-03 06:15 UTC, pyToshka approved these changes

2024-05-03 06:15 UTC, merged

2024-05-07 09:39 UTC, sfc-gh-gmerticariu commented
@pyToshka thank you for merging it! Could you please create a new release, so the changes are reflected?